apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-wlwc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-wlwc
    app.kubernetes.io/part-of: test-app-678
  name: maven-hello-world-wlwc
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: maven-hello-world-wlwc
status:
  loadBalancer: {}
