apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-nkf0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-nkf0
    app.kubernetes.io/part-of: test-app-678
  name: retrodep-nkf0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-nkf0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-nkf0
    spec:
      containers:
      - image: retrodep:latest
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
