apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-sample-repo-qwwp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-sample-repo-qwwp
    app.kubernetes.io/part-of: test-app-678
  name: fbc-sample-repo-qwwp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: fbc-sample-repo-qwwp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: fbc-sample-repo-qwwp
    spec:
      containers:
      - image: fbc:latest
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
